### ISSUE TITLE
Running initial migration causes error 

### ISSUE THREAD

**Issue by thisisthechris** [i-DAT-Qualia/Qualia-Core#3]
``` shell
vagrant@packer-wheezy64-ansible-1437663235:/var/www/qualia$ python manage.py migrate
/usr/local/lib/python2.7/dist-packages/django/contrib/sites/models.py:78: RemovedInDjango19Warning: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Site(models.Model):

Operations to perform:
  Synchronize unmigrated apps: oauth2, gis, postgres, staticfiles, messages, imagekit, leaflet, provider
  Apply all migrations: sessions, admin, tastypie, auth, contenttypes, accounts, registration
Synchronizing apps without migrations:
  Creating tables...
    Creating table oauth2_client
    Creating table oauth2_grant
    Creating table oauth2_accesstoken
    Creating table oauth2_refreshtoken
    Running deferred SQL...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 317, in sync_apps
    cursor.execute(statement)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "accounts_qualiauser" does not exist
```

Can be worked around by disabling the provider and provider.oauth steps. Might need to upgrade and fix dependancies

**Comment by thisisthechris** [comment]
Upgrade to https://github.com/evonove/django-oauth-toolkit
